name: Azure Data Factory CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        #pip install -r requirements.txt
      
    - name: Authenticate with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure ADF
      uses: miyas000/pipeline_demo@main
      with:
        resource-group: ce2-cndat-rg-np-odp09
        data-factory-name:  ce2-cndat-df-np-odp07
        git-repo-url: https://github.com/Changsensen7/pipeline_demo.git
      env:
        azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
