name: Azure Data Factory CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Authenticate with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure ADF
      uses: miyas000/azure-adf-deploy@main
      with:
        resource-group: my-resource-group
        data-factory-name: my-data-factory
        git-repo-url: https://github.com/username/repository-name.git
      env:
        azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
